(()=>{'use strict';
const RADAR='https://api.rainviewer.com/public/weather-maps.json';
const MODELS={cma:{label:'CMA GRAPES',url:'https://api.open-meteo.com/v1/cma'},ecmwf:{label:'ECMWF IFS',url:'https://api.open-meteo.com/v1/ecmwf'},gfs:{label:'NCEP GFS',url:'https://api.open-meteo.com/v1/gfs'}};
const P={radar:['天气雷达','RainViewer Radar','radar','真实组合雷达回波；无覆盖区域保持空白。'],cloud:['模式云场','Open-Meteo model data','cloud','总云量模式场，不等同于卫星云图。'],precip72:['未来 72 小时累计降水','Open-Meteo model data','precip','逐小时降水累计，单位 mm。'],wind850:['850 hPa 风场','Open-Meteo pressure levels','wind','850 hPa 风速填色和风向箭头。'],height500:['500 hPa 高度与温度场','Open-Meteo pressure levels','temp','500 hPa 温度与位势高度分析。'],sounding:['模式探空图','Open-Meteo pressure levels','temp','温度、露点、风和高度的模式垂直廓线。']};
const $=id=>document.getElementById(id);const E={status:$('statusBadge'),title:$('productTitle'),desc:$('productDescription'),source:$('sourceText'),valid:$('validTime'),modelText:$('modelText'),notes:$('productNotes'),legend:$('legendBar'),labels:$('legendLabels'),model:$('modelSelect'),fh:$('forecastHour'),modelControl:$('modelControl'),forecastControl:$('forecastControl'),radarControl:$('radarTimeControl'),radarTime:$('radarTime'),radarPlay:$('radarPlay'),precipControl:$('precipRangeControl'),precipRange:$('precipRange'),soundControl:$('soundingControl'),lat:$('soundLat'),lon:$('soundLon'),city:$('cityQuery'),citySearch:$('citySearch'),loadSound:$('loadSounding'),refresh:$('refreshBtn'),loading:$('loadingOverlay'),mapEl:$('map'),chart:$('soundingChart')};
let map,radarLayer,fieldLayer,frames=[],radarHost='',timer=null,state={product:'radar',model:'cma',fh:0};
for(let h=0;h<=72;h+=3){const o=document.createElement('option');o.value=h;o.textContent=`+${String(h).padStart(2,'0')} h`;E.fh.append(o)}
function status(t){E.status.textContent=t}function loading(v){E.loading.classList.toggle('hidden',!v)}function fmt(t){if(!t)return'—';const d=new Date(typeof t==='number'?t*1000:t);return isNaN(d)?String(t):d.toLocaleString('zh-CN',{hour12:false})}
function initMap(){map=L.map('map',{minZoom:3,maxZoom:9}).setView([35,105],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:9,attribution:'&copy; OpenStreetMap contributors'}).addTo(map)}
function clear(){if(radarLayer){map.removeLayer(radarLayer);radarLayer=null}if(fieldLayer){map.removeLayer(fieldLayer);fieldLayer=null}}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.reason||'数据源错误');return d}
function endpoint(params){return MODELS[state.model].url+'?'+new URLSearchParams(params).toString()}
function ui(){const p=P[state.product];E.title.textContent=p[0];E.desc.textContent=p[3];E.source.textContent=p[1];E.notes.innerHTML=`<p>${p[3]}</p>`;E.legend.className=`legend-bar ${p[2]}`;E.labels.innerHTML='<span>低</span><span>高</span>';E.modelControl.classList.toggle('hidden',state.product==='radar');E.forecastControl.classList.toggle('hidden',['radar','precip72'].includes(state.product));E.radarControl.classList.toggle('hidden',state.product!=='radar');E.radarPlay.classList.toggle('hidden',state.product!=='radar');E.precipControl.classList.toggle('hidden',state.product!=='precip72');E.soundControl.classList.toggle('hidden',state.product!=='sounding');E.mapEl.classList.toggle('hidden',state.product==='sounding');E.chart.classList.toggle('hidden',state.product!=='sounding');E.modelText.textContent=state.product==='radar'?'实况雷达':MODELS[state.model].label;setTimeout(()=>map&&state.product!=='sounding'&&map.invalidateSize(),0)}
function color(v,min,max,colors){if(!Number.isFinite(v))return'#334555';const x=Math.max(0,Math.min(1,(v-min)/(max-min))),i=Math.min(colors.length-1,Math.floor(x*colors.length));return colors[i]}
function grid(){const pts=[];for(const lat of [18,24,30,36,42,48,54])for(const lon of [75,82.5,90,97.5,105,112.5,120,127.5,135])pts.push({lat,lon});return pts}
async function fetchGrid(vars,hours=73){const pts=grid(),d=await json(endpoint({latitude:pts.map(p=>p.lat).join(','),longitude:pts.map(p=>p.lon).join(','),hourly:vars.join(','),forecast_hours:String(hours),timezone:'GMT',wind_speed_unit:'ms'}));return{pts,res:Array.isArray(d)?d:[d]}}
function render(pts,vals,min,max,colors,unit,extra){fieldLayer=L.layerGroup().addTo(map);pts.forEach((p,i)=>{const v=Number(vals[i]);L.circleMarker([p.lat,p.lon],{radius:18,stroke:false,fillOpacity:.62,fillColor:color(v,min,max,colors)}).bindTooltip(`${p.lat}°, ${p.lon}°<br><b>${Number.isFinite(v)?v.toFixed(1):'—'} ${unit}</b>${extra?.[i]?'<br>'+extra[i]:''}`).addTo(fieldLayer)})}
async function radar(){clear();const d=await json(RADAR);frames=d.radar?.past||[];radarHost=d.host||'https://tilecache.rainviewer.com';if(!frames.length)throw new Error('暂无雷达时次');E.radarTime.max=frames.length-1;E.radarTime.value=frames.length-1;showRadar(frames.length-1)}
function showRadar(i){if(!frames.length)return;if(radarLayer)map.removeLayer(radarLayer);const f=frames[Math.max(0,Math.min(i,frames.length-1))];radarLayer=L.tileLayer(`${radarHost}${f.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.72,zIndex:500}).addTo(map);E.valid.textContent=fmt(f.time);status('雷达已更新')}
async function cloud(){clear();const {pts,res}=await fetchGrid(['cloud_cover']);const vals=res.map(r=>r.hourly?.cloud_cover?.[state.fh]);render(pts,vals,0,100,['#223648','#64798a','#b9c7d0','#fff'],'%');E.valid.textContent=fmt(res[0].hourly.time[state.fh])}
async function precip(){clear();const {pts,res}=await fetchGrid(['precipitation'],73),[a,b]=E.precipRange.value.split('-').map(Number);const vals=res.map(r=>(r.hourly?.precipitation||[]).slice(a,b).reduce((s,v)=>s+(Number(v)||0),0));render(pts,vals,0,150,['#12366f','#176dff','#1bc7a4','#f8e83d','#ff8a2a','#e7333c','#8a2cad'],'mm');E.valid.textContent=`${fmt(res[0].hourly.time[a])} → ${fmt(res[0].hourly.time[Math.max(a,b-1)])}`}
async function wind(){clear();const {pts,res}=await fetchGrid(['wind_speed_850hPa','wind_direction_850hPa']);const s=res.map(r=>r.hourly?.wind_speed_850hPa?.[state.fh]),d=res.map(r=>r.hourly?.wind_direction_850hPa?.[state.fh]);render(pts,s,0,40,['#295f8b','#31a8bd','#72c879','#e8d94f','#c93b43'],'m/s',d.map(x=>`风向 ${Number(x).toFixed(0)}°`));pts.forEach((p,i)=>{if(!Number.isFinite(Number(d[i])))return;const ic=L.divIcon({className:'',html:`<div class="wind-arrow" style="transform:rotate(${Number(d[i])+180}deg)">↑</div>`,iconSize:[20,20]});L.marker([p.lat,p.lon],{icon:ic,interactive:false}).addTo(fieldLayer)});E.valid.textContent=fmt(res[0].hourly.time[state.fh])}
async function height(){clear();const {pts,res}=await fetchGrid(['temperature_500hPa','geopotential_height_500hPa']);const t=res.map(r=>r.hourly?.temperature_500hPa?.[state.fh]),h=res.map(r=>r.hourly?.geopotential_height_500hPa?.[state.fh]);render(pts,t,-40,0,['#5133a6','#3374d6','#57c8cf','#d7df71','#d64545'],'°C',h.map(x=>`H500 ${Number(x).toFixed(0)} m`));E.valid.textContent=fmt(res[0].hourly.time[state.fh])}
function dew(t,rh){const a=17.625,b=243.04,x=Math.log(Math.max(1,Math.min(100,rh))/100)+a*t/(b+t);return b*x/(a-x)}
async function sounding(){clear();const levels=[1000,925,850,700,600,500,400,300,250,200,150,100],vars=[];levels.forEach(p=>vars.push(`temperature_${p}hPa`,`relative_humidity_${p}hPa`,`wind_speed_${p}hPa`,`wind_direction_${p}hPa`,`geopotential_height_${p}hPa`));const r=await json(endpoint({latitude:E.lat.value,longitude:E.lon.value,hourly:vars.join(','),forecast_hours:'73',timezone:'GMT',wind_speed_unit:'ms'})),i=state.fh,t=levels.map(p=>Number(r.hourly?.[`temperature_${p}hPa`]?.[i])),rh=levels.map(p=>Number(r.hourly?.[`relative_humidity_${p}hPa`]?.[i])),td=t.map((x,j)=>dew(x,rh[j]));await Plotly.react(E.chart,[{x:t,y:levels,mode:'lines+markers',name:'温度'},{x:td,y:levels,mode:'lines+markers',name:'露点'}],{paper_bgcolor:'#07141f',plot_bgcolor:'#07141f',font:{color:'#dcecf5'},margin:{l:70,r:30,t:50,b:55},title:'模式探空',xaxis:{title:'温度 / 露点 (°C)'},yaxis:{title:'气压 (hPa)',type:'log',autorange:'reversed',tickvals:levels}},{responsive:true,displaylogo:false});E.valid.textContent=fmt(r.hourly.time[i])}
async function city(){const q=E.city.value.trim();if(!q)return;const d=await json(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=zh&format=json`),p=d.results?.[0];if(!p)throw new Error('未找到城市');E.lat.value=Number(p.latitude).toFixed(2);E.lon.value=Number(p.longitude).toFixed(2);E.city.value=p.name||q;load()}
async function load(){ui();loading(true);status('加载中…');try{if(state.product==='radar')await radar();if(state.product==='cloud')await cloud();if(state.product==='precip72')await precip();if(state.product==='wind850')await wind();if(state.product==='height500')await height();if(state.product==='sounding')await sounding();if(state.product!=='radar')status('数据已更新')}catch(e){console.error(e);status('加载失败');E.notes.innerHTML+=`<p><strong>错误：</strong>${String(e.message||e)}</p>`}finally{loading(false)}}
document.querySelectorAll('.product-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.product-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.product=b.dataset.product;load()});E.model.onchange=()=>{state.model=E.model.value;load()};E.fh.onchange=()=>{state.fh=Number(E.fh.value);load()};E.radarTime.oninput=()=>showRadar(Number(E.radarTime.value));E.radarPlay.onclick=()=>{if(timer){clearInterval(timer);timer=null;E.radarPlay.textContent='播放雷达'}else{timer=setInterval(()=>{E.radarTime.value=(Number(E.radarTime.value)+1)%frames.length;showRadar(Number(E.radarTime.value))},700);E.radarPlay.textContent='暂停雷达'}};E.precipRange.onchange=load;E.citySearch.onclick=()=>city().catch(e=>status(e.message));E.loadSound.onclick=load;E.refresh.onclick=load;initMap();ui();load();
})();
