import{bilinear,contourSegments,kIndex,lclPressure,skewX,totalTotals,windBarbSvg}from'./meteo.mjs';
const RADAR='https://api.rainviewer.com/public/weather-maps.json';
const MODELS={cma:{label:'CMA GRAPES',url:'https://api.open-meteo.com/v1/cma',diagnostics:['cape','convective_inhibition','lifted_index']},ecmwf:{label:'ECMWF IFS',url:'https://api.open-meteo.com/v1/ecmwf',diagnostics:['cape']},gfs:{label:'NCEP GFS',url:'https://api.open-meteo.com/v1/gfs',diagnostics:['cape','convective_inhibition','lifted_index']}};
const P={radar:['天气雷达','RainViewer Radar','radar','真实组合雷达回波；无覆盖区域保持空白。'],cloud:['模式云场','Open-Meteo model data','cloud','总云量模式场，不等同于卫星云图。'],precip72:['未来 72 小时累计降水','Open-Meteo model data','precip','逐小时降水累计，单位 mm。'],wind850:['850 hPa 风场','Open-Meteo pressure levels','wind','850 hPa 连续风速底图 + 标准风羽。'],height500:['500 hPa 高度与温度场','Open-Meteo pressure levels','temp','500 hPa 温度连续填色 + 位势高度等值线。'],sounding:['模式探空图','Open-Meteo pressure levels','temp','Skew‑T/Log‑P 风格温湿廓线、风羽和稳定度指标。']};
const LATS=[15,20,25,30,35,40,45,50,55],LONS=[75,81,87,93,99,105,111,117,123,129,135],LEVELS=[1000,925,850,700,600,500,400,300,250,200,150,100],$=id=>document.getElementById(id);
const E={status:$('statusBadge'),title:$('productTitle'),desc:$('productDescription'),source:$('sourceText'),valid:$('validTime'),modelText:$('modelText'),notes:$('productNotes'),legend:$('legendBar'),labels:$('legendLabels'),model:$('modelSelect'),fh:$('forecastHour'),modelControl:$('modelControl'),forecastControl:$('forecastControl'),radarControl:$('radarTimeControl'),radarTime:$('radarTime'),radarPlay:$('radarPlay'),precipControl:$('precipRangeControl'),precipRange:$('precipRange'),soundControl:$('soundingControl'),lat:$('soundLat'),lon:$('soundLon'),city:$('cityQuery'),citySearch:$('citySearch'),loadSound:$('loadSounding'),refresh:$('refreshBtn'),loading:$('loadingOverlay'),mapEl:$('map'),chart:$('soundingChart'),metrics:$('soundingMetrics')};
let map,radarLayer,fieldLayer,frames=[],radarHost='',timer=null;const state={product:'radar',model:'cma',fh:0};
for(let h=0;h<=72;h+=3){const o=document.createElement('option');o.value=h;o.textContent=`+${String(h).padStart(2,'0')} h`;E.fh.append(o)}
const status=t=>E.status.textContent=t,loading=v=>E.loading.classList.toggle('hidden',!v),fmt=t=>{if(!t)return'—';const d=new Date(typeof t==='number'?t*1000:t);return Number.isNaN(d.valueOf())?String(t):d.toLocaleString('zh-CN',{hour12:false})};
function initMap(){map=L.map('map',{minZoom:3,maxZoom:9}).setView([35,105],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:9,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);map.on('click',e=>{E.lat.value=e.latlng.lat.toFixed(2);E.lon.value=e.latlng.lng.toFixed(2);status('已记录模式探空选点')})}
function clear(){if(radarLayer){map.removeLayer(radarLayer);radarLayer=null}if(fieldLayer){map.removeLayer(fieldLayer);fieldLayer=null}}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.reason||'数据源错误');return d}
const endpoint=params=>MODELS[state.model].url+'?'+new URLSearchParams(params).toString();
function ui(){const p=P[state.product];E.title.textContent=p[0];E.desc.textContent=p[3];E.source.textContent=p[1];E.notes.innerHTML=`<p>${p[3]}</p>`;E.legend.className=`legend-bar ${p[2]}`;E.labels.innerHTML='<span>低</span><span>高</span>';E.modelControl.classList.toggle('hidden',state.product==='radar');E.forecastControl.classList.toggle('hidden',['radar','precip72'].includes(state.product));E.radarControl.classList.toggle('hidden',state.product!=='radar');E.radarPlay.classList.toggle('hidden',state.product!=='radar');E.precipControl.classList.toggle('hidden',state.product!=='precip72');E.soundControl.classList.toggle('hidden',state.product!=='sounding');E.mapEl.classList.toggle('hidden',state.product==='sounding');E.chart.classList.toggle('hidden',state.product!=='sounding');E.metrics.classList.toggle('hidden',state.product!=='sounding');E.modelText.textContent=state.product==='radar'?'实况雷达':MODELS[state.model].label;setTimeout(()=>map&&state.product!=='sounding'&&map.invalidateSize(),0)}
function rgba(v,min,max,colors){if(!Number.isFinite(v))return[51,69,85,0];const x=Math.max(0,Math.min(1,(v-min)/(max-min)))*(colors.length-1),i=Math.min(colors.length-2,Math.floor(x)),f=x-i,parse=h=>h.match(/\w\w/g).map(z=>parseInt(z,16)),a=parse(colors[i]),b=parse(colors[i+1]);return[Math.round(a[0]+(b[0]-a[0])*f),Math.round(a[1]+(b[1]-a[1])*f),Math.round(a[2]+(b[2]-a[2])*f),220]}
function points(){const pts=[];for(const lat of LATS)for(const lon of LONS)pts.push({lat,lon});return pts}
async function fetchGrid(vars,hours=73){const pts=points(),d=await json(endpoint({latitude:pts.map(p=>p.lat).join(','),longitude:pts.map(p=>p.lon).join(','),hourly:vars.join(','),forecast_hours:String(hours),timezone:'GMT',wind_speed_unit:'ms'}));return Array.isArray(d)?d:[d]}
function matrix(res,key,index){const out=[];for(let r=0;r<LATS.length;r++){const row=[];for(let c=0;c<LONS.length;c++)row.push(Number(res[r*LONS.length+c]?.hourly?.[key]?.[index]));out.push(row)}return out}
function sumMatrix(res,key,a,b){const out=[];for(let r=0;r<LATS.length;r++){const row=[];for(let c=0;c<LONS.length;c++){const arr=res[r*LONS.length+c]?.hourly?.[key]||[];row.push(arr.slice(a,b).reduce((s,v)=>s+(Number(v)||0),0))}out.push(row)}return out}
const flat=m=>m.flat().filter(Number.isFinite);
function raster(values,min,max,colors,opacity=.68){const canvas=document.createElement('canvas'),w=520,h=340;canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d'),img=ctx.createImageData(w,h),rows=values.length,cols=values[0].length;for(let y=0;y<h;y++){const gy=(1-y/(h-1))*(rows-1),r=Math.min(rows-2,Math.floor(gy)),ty=gy-r;for(let x=0;x<w;x++){const gx=x/(w-1)*(cols-1),c=Math.min(cols-2,Math.floor(gx)),tx=gx-c,v=bilinear(values[r][c],values[r][c+1],values[r+1][c],values[r+1][c+1],tx,ty),q=rgba(v,min,max,colors),i=(y*w+x)*4;img.data[i]=q[0];img.data[i+1]=q[1];img.data[i+2]=q[2];img.data[i+3]=q[3]}}ctx.putImageData(img,0,0);L.imageOverlay(canvas.toDataURL('image/png'),[[LATS[0],LONS[0]],[LATS.at(-1),LONS.at(-1)]],{opacity,interactive:false}).addTo(fieldLayer)}
function addBarbs(speed,dir){for(let r=0;r<LATS.length;r+=2)for(let c=0;c<LONS.length;c+=2){const s=speed[r][c],d=dir[r][c];if(!Number.isFinite(s)||!Number.isFinite(d))continue;L.marker([LATS[r],LONS[c]],{icon:L.divIcon({className:'wind-barb-icon',html:windBarbSvg(s,d,{size:42}),iconSize:[42,42],iconAnchor:[21,21]}),interactive:false}).addTo(fieldLayer)}}
function addContours(hgt){const vals=flat(hgt);if(!vals.length)return;for(let level=Math.ceil(Math.min(...vals)/60)*60;level<=Math.floor(Math.max(...vals)/60)*60;level+=60){const segs=contourSegments(hgt,LATS,LONS,level);segs.forEach((seg,i)=>{L.polyline(seg,{color:'#f5f9ff',weight:1.25,opacity:.82,interactive:false}).addTo(fieldLayer);if(i===0){const mid=[(seg[0][0]+seg[1][0])/2,(seg[0][1]+seg[1][1])/2];L.marker(mid,{interactive:false,icon:L.divIcon({className:'contour-label',html:String(level),iconSize:[38,16],iconAnchor:[19,8]})}).addTo(fieldLayer)}})}}
async function radar(){clear();const d=await json(RADAR);frames=d.radar?.past||[];radarHost=d.host||'https://tilecache.rainviewer.com';if(!frames.length)throw new Error('暂无雷达时次');E.radarTime.max=frames.length-1;E.radarTime.value=frames.length-1;showRadar(frames.length-1)}
function showRadar(i){if(!frames.length)return;if(radarLayer)map.removeLayer(radarLayer);const f=frames[Math.max(0,Math.min(i,frames.length-1))];radarLayer=L.tileLayer(`${radarHost}${f.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.72,zIndex:500}).addTo(map);E.valid.textContent=fmt(f.time);status('雷达已更新')}
async function cloud(){clear();fieldLayer=L.layerGroup().addTo(map);const r=await fetchGrid(['cloud_cover']),m=matrix(r,'cloud_cover',state.fh);raster(m,0,100,['#12273a','#607487','#d9e3e9','#ffffff'],.62);E.valid.textContent=fmt(r[0]?.hourly?.time?.[state.fh]);E.notes.innerHTML+='<p>展示为模式采样网格的平滑可视化，并非原始模式全分辨率格点。</p>'}
async function precip(){clear();fieldLayer=L.layerGroup().addTo(map);const r=await fetchGrid(['precipitation'],73),[a,b]=E.precipRange.value.split('-').map(Number),m=sumMatrix(r,'precipitation',a,b),hi=Math.max(20,...flat(m));raster(m,0,Math.min(200,hi),['#102c5c','#1675ff','#20d3a7','#fff23f','#ed7b2f','#ed2f3b','#9d2fbd'],.72);E.valid.textContent=`${fmt(r[0]?.hourly?.time?.[a])} → ${fmt(r[0]?.hourly?.time?.[Math.max(a,b-1)])}`}
async function wind(){clear();fieldLayer=L.layerGroup().addTo(map);const r=await fetchGrid(['wind_speed_850hPa','wind_direction_850hPa']),s=matrix(r,'wind_speed_850hPa',state.fh),d=matrix(r,'wind_direction_850hPa',state.fh),hi=Math.max(20,...flat(s));raster(s,0,Math.min(50,hi),['#295f8b','#31a8bd','#72c879','#e8d94f','#c93b43'],.7);addBarbs(s,d);E.valid.textContent=fmt(r[0]?.hourly?.time?.[state.fh]);E.notes.innerHTML+='<p>风羽按 5 kt 取整；三角旗=50 kt，长羽=10 kt，短羽=5 kt。</p>'}
async function height(){clear();fieldLayer=L.layerGroup().addTo(map);const r=await fetchGrid(['temperature_500hPa','geopotential_height_500hPa']),t=matrix(r,'temperature_500hPa',state.fh),h=matrix(r,'geopotential_height_500hPa',state.fh),tv=flat(t);raster(t,Math.min(-40,...tv),Math.max(-2,...tv),['#5133a6','#3374d6','#57c8cf','#d7df71','#d64545'],.7);addContours(h);E.valid.textContent=fmt(r[0]?.hourly?.time?.[state.fh]);E.notes.innerHTML+='<p>白色等值线为 500 hPa 位势高度，间隔 60 m；底色为 500 hPa 温度。</p>'}
function dew(t,rh){const a=17.625,b=243.04,x=Math.log(Math.max(1,Math.min(100,Number(rh)))/100)+a*Number(t)/(b+Number(t));return b*x/(a-x)}
function soundVars(){const v=['temperature_2m','dew_point_2m','surface_pressure',...MODELS[state.model].diagnostics];for(const p of LEVELS)v.push(`temperature_${p}hPa`,`relative_humidity_${p}hPa`,`wind_speed_${p}hPa`,`wind_direction_${p}hPa`,`geopotential_height_${p}hPa`);return v}
const metric=(l,v,u='',h='')=>`<div class="metric"><span>${l}</span><strong>${v}${u}</strong>${h?`<small>${h}</small>`:''}</div>`;
function metrics(r,i,t){const h=r.hourly||{},v=k=>Number(h[k]?.[i]),td850=dew(t[2],v('relative_humidity_850hPa')),td700=dew(t[3],v('relative_humidity_700hPa')),ki=kIndex({t850:t[2],t700:t[3],t500:t[5],td850,td700}),tt=totalTotals({t850:t[2],t500:t[5],td850}),lcl=lclPressure(v('temperature_2m'),v('dew_point_2m'),v('surface_pressure')),cape=v('cape'),cin=v('convective_inhibition'),li=v('lifted_index');return[metric('CAPE',Number.isFinite(cape)?cape.toFixed(0):'—',Number.isFinite(cape)?' J/kg':''),metric('CIN',Number.isFinite(cin)?cin.toFixed(0):'—',Number.isFinite(cin)?' J/kg':'','部分模式不提供'),metric('抬升指数',Number.isFinite(li)?li.toFixed(1):'—','','部分模式不提供'),metric('LCL',Number.isFinite(lcl)?lcl.toFixed(0):'—',Number.isFinite(lcl)?' hPa':''),metric('K 指数',Number.isFinite(ki)?ki.toFixed(1):'—'),metric('TT 指数',Number.isFinite(tt)?tt.toFixed(1):'—')].join('')}
function gridTraces(){const p=[1050,1000,925,850,700,600,500,400,300,250,200,150,100],tr=[];for(let iso=-80;iso<=50;iso+=10)tr.push({x:p.map(x=>skewX(iso,x)),y:p,mode:'lines',line:{color:'rgba(190,210,220,.18)',width:1},hoverinfo:'skip',showlegend:false});for(let th=250;th<=430;th+=20){const tc=p.map(x=>th*Math.pow(x/1000,.2854)-273.15);tr.push({x:tc.map((v,j)=>skewX(v,p[j])),y:p,mode:'lines',line:{color:'rgba(229,176,80,.12)',width:1},hoverinfo:'skip',showlegend:false})}return tr}
function windImages(s,d){return LEVELS.map((p,i)=>({source:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(windBarbSvg(s[i],d[i],{size:48})),xref:'paper',yref:'paper',x:1.035,y:(Math.log(1000)-Math.log(p))/(Math.log(1000)-Math.log(100)),sizex:.075,sizey:.075,xanchor:'center',yanchor:'middle',layer:'above'}))}
async function sounding(){clear();const r=await json(endpoint({latitude:E.lat.value,longitude:E.lon.value,hourly:soundVars().join(','),forecast_hours:'73',timezone:'GMT',wind_speed_unit:'ms'})),i=state.fh,h=r.hourly||{},t=LEVELS.map(p=>Number(h[`temperature_${p}hPa`]?.[i])),rh=LEVELS.map(p=>Number(h[`relative_humidity_${p}hPa`]?.[i])),td=t.map((x,j)=>dew(x,rh[j])),s=LEVELS.map(p=>Number(h[`wind_speed_${p}hPa`]?.[i])),d=LEVELS.map(p=>Number(h[`wind_direction_${p}hPa`]?.[i])),tr=[...gridTraces(),{x:t.map((v,j)=>skewX(v,LEVELS[j])),y:LEVELS,customdata:t,mode:'lines+markers',name:'温度',line:{width:3},hovertemplate:'%{y} hPa<br>T %{customdata:.1f} °C<extra></extra>'},{x:td.map((v,j)=>skewX(v,LEVELS[j])),y:LEVELS,customdata:td,mode:'lines+markers',name:'露点',line:{width:3},hovertemplate:'%{y} hPa<br>Td %{customdata:.1f} °C<extra></extra>'}],ticks=[];for(let x=-50;x<=50;x+=10)ticks.push(x);await Plotly.react(E.chart,tr,{paper_bgcolor:'#07141f',plot_bgcolor:'#07141f',font:{color:'#dcecf5'},margin:{l:72,r:110,t:54,b:58},title:{text:'模式 Skew‑T / Log‑P',x:.02},xaxis:{title:'等温线基准温度 (°C)',range:[-55,85],tickvals:ticks,ticktext:ticks,gridcolor:'rgba(255,255,255,.06)',zeroline:false},yaxis:{title:'气压 (hPa)',type:'log',range:[Math.log10(1050),Math.log10(100)],tickvals:LEVELS,autorange:'reversed',gridcolor:'rgba(255,255,255,.12)'},images:windImages(s,d),legend:{orientation:'h',x:.02,y:1.08}},{responsive:true,displaylogo:false});E.metrics.innerHTML=metrics(r,i,t);E.valid.textContent=fmt(h.time?.[i]);E.notes.innerHTML+='<p>右侧为标准风羽。背景斜线为等温线，暖色细线为干绝热线。</p><p>CIN/抬升指数仅在所选模式原生提供时显示；LCL、K 指数、TT 指数由当前模式廓线计算。</p>'}
async function city(){const q=E.city.value.trim();if(!q)return;const d=await json(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=zh&format=json`),p=d.results?.[0];if(!p)throw new Error('未找到城市');E.lat.value=Number(p.latitude).toFixed(2);E.lon.value=Number(p.longitude).toFixed(2);E.city.value=p.name||q;load()}
async function load(){ui();loading(true);status('加载中…');try{if(state.product==='radar')await radar();if(state.product==='cloud')await cloud();if(state.product==='precip72')await precip();if(state.product==='wind850')await wind();if(state.product==='height500')await height();if(state.product==='sounding')await sounding();if(state.product!=='radar')status('数据已更新')}catch(e){console.error(e);status('加载失败');E.notes.innerHTML+=`<p><strong>错误：</strong>${String(e.message||e)}</p>`}finally{loading(false)}}
document.querySelectorAll('.product-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.product-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.product=b.dataset.product;load()});E.model.onchange=()=>{state.model=E.model.value;load()};E.fh.onchange=()=>{state.fh=Number(E.fh.value);load()};E.radarTime.oninput=()=>showRadar(Number(E.radarTime.value));E.radarPlay.onclick=()=>{if(timer){clearInterval(timer);timer=null;E.radarPlay.textContent='播放雷达'}else{timer=setInterval(()=>{E.radarTime.value=(Number(E.radarTime.value)+1)%frames.length;showRadar(Number(E.radarTime.value))},700);E.radarPlay.textContent='暂停雷达'}};E.precipRange.onchange=load;E.citySearch.onclick=()=>city().catch(e=>status(e.message));E.loadSound.onclick=load;E.refresh.onclick=load;initMap();ui();load();
