const MODELS={cma:'https://api.open-meteo.com/v1/cma',ecmwf:'https://api.open-meteo.com/v1/ecmwf',gfs:'https://api.open-meteo.com/v1/gfs'};
const LATS=[15,20,25,30,35,40,45,50,55],LONS=[75,81,87,93,99,105,111,117,123,129,135];
const $=id=>document.getElementById(id);let dmap,layer,active=null;
function points(){const a=[];for(const lat of LATS)for(const lon of LONS)a.push({lat,lon});return a}
async function fetchGrid(vars){const pts=points(),model=$('modelSelect')?.value||'cma',fh=Number($('forecastHour')?.value||0);const q=new URLSearchParams({latitude:pts.map(p=>p.lat).join(','),longitude:pts.map(p=>p.lon).join(','),hourly:vars.join(','),forecast_hours:'73',timezone:'GMT',wind_speed_unit:'ms'});const r=await fetch(`${MODELS[model]}?${q}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json(),res=Array.isArray(d)?d:[d];return{res,fh}}
function matrix(res,key,i){const out=[];for(let r=0;r<LATS.length;r++){const row=[];for(let c=0;c<LONS.length;c++)row.push(Number(res[r*LONS.length+c]?.hourly?.[key]?.[i]));out.push(row)}return out}
function flat(m){return m.flat().filter(Number.isFinite)}
function bilinear(a,b,c,d,x,y){return a*(1-x)*(1-y)+b*x*(1-y)+c*(1-x)*y+d*x*y}
function rgba(v,min,max,pal){if(!Number.isFinite(v))return[0,0,0,0];const z=Math.max(0,Math.min(1,(v-min)/(max-min)))*(pal.length-1),i=Math.min(pal.length-2,Math.floor(z)),f=z-i,hex=h=>h.match(/\w\w/g).map(x=>parseInt(x,16)),a=hex(pal[i]),b=hex(pal[i+1]);return[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,a[2]+(b[2]-a[2])*f,220]}
function ensureMap(){if(dmap)return;dmap=L.map('dynamicsMap',{minZoom:3,maxZoom:9}).setView([35,105],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:9,attribution:'&copy; OpenStreetMap contributors'}).addTo(dmap)}
function draw(m,min,max,pal){ensureMap();if(layer)dmap.removeLayer(layer);const c=document.createElement('canvas'),w=520,h=340;c.width=w;c.height=h;const x=c.getContext('2d'),img=x.createImageData(w,h);for(let py=0;py<h;py++){const gy=(1-py/(h-1))*(m.length-1),r=Math.min(m.length-2,Math.floor(gy)),ty=gy-r;for(let px=0;px<w;px++){const gx=px/(w-1)*(m[0].length-1),cc=Math.min(m[0].length-2,Math.floor(gx)),tx=gx-cc,v=bilinear(m[r][cc],m[r][cc+1],m[r+1][cc],m[r+1][cc+1],tx,ty),q=rgba(v,min,max,pal),k=(py*w+px)*4;img.data[k]=q[0];img.data[k+1]=q[1];img.data[k+2]=q[2];img.data[k+3]=q[3]}}x.putImageData(img,0,0);layer=L.imageOverlay(c.toDataURL(),[[LATS[0],LONS[0]],[LATS.at(-1),LONS.at(-1)]],{opacity:.72}).addTo(dmap);setTimeout(()=>dmap.invalidateSize(),0)}
function uv(speed,dir){const u=[],v=[];for(let r=0;r<speed.length;r++){u[r]=[];v[r]=[];for(let c=0;c<speed[r].length;c++){const th=(Number(dir[r][c])||0)*Math.PI/180,s=Number(speed[r][c]);u[r][c]=-s*Math.sin(th);v[r][c]=-s*Math.cos(th)}}return{u,v}}
export function horizontalDerivatives(speed,dir){const {u,v}=uv(speed,dir),R=6371000,div=[],vor=[];for(let r=0;r<LATS.length;r++){div[r]=[];vor[r]=[];for(let c=0;c<LONS.length;c++){const rm=Math.max(0,r-1),rp=Math.min(LATS.length-1,r+1),cm=Math.max(0,c-1),cp=Math.min(LONS.length-1,c+1),lat=LATS[r]*Math.PI/180,dx=R*Math.cos(lat)*(LONS[cp]-LONS[cm])*Math.PI/180,dy=R*(LATS[rp]-LATS[rm])*Math.PI/180,dudx=(u[r][cp]-u[r][cm])/dx,dvdx=(v[r][cp]-v[r][cm])/dx,dudy=(u[rp][c]-u[rm][c])/dy,dvdy=(v[rp][c]-v[rm][c])/dy;div[r][c]=(dudx+dvdy)*1e5;vor[r][c]=(dvdx-dudy)*1e5}}return{divergence:div,vorticity:vor}}
function activate(title,source,note){active=title;$('map').classList.add('hidden');$('soundingChart').classList.add('hidden');$('soundingMetrics').classList.add('hidden');$('dynamicsMap').classList.remove('hidden');$('productTitle').textContent=title;$('productDescription').textContent=note;$('sourceText').textContent=source;$('modelText').textContent=$('modelSelect').selectedOptions[0]?.textContent||'模式';$('productNotes').innerHTML=`<p>${note}</p>`}
async function omega(level){activate(`${level} hPa 垂直速度`,'Open-Meteo pressure levels',`模式原生 ${level} hPa 垂直速度场；按数据源原单位显示，负值通常对应上升运动。`);const key=`vertical_velocity_${level}hPa`,{res,fh}=await fetchGrid([key]),m=matrix(res,key,fh),a=Math.max(.2,...flat(m).map(Math.abs));draw(m,-a,a,['#3f2f8f','#3c78c4','#66c5c7','#f0f0df','#e5a45a','#b94242']);$('validTime').textContent=res[0]?.hourly?.time?.[fh]||'—'}
export async function omega700(){return omega(700)} export async function omega500(){return omega(500)}
async function windDiag(level,type){const sKey=`wind_speed_${level}hPa`,dKey=`wind_direction_${level}hPa`,{res,fh}=await fetchGrid([sKey,dKey]),s=matrix(res,sKey,fh),d=matrix(res,dKey,fh),q=horizontalDerivatives(s,d),m=type==='vor'?q.vorticity:q.divergence,a=Math.max(1,...flat(m).map(Math.abs)),title=type==='vor'?`${level} hPa 涡度`:`${level} hPa 散度`;activate(title,'Open-Meteo wind → derived',`由模式风速/风向在当前采样网格上采用球面有限差分派生，单位显示为 10⁻⁵ s⁻¹；属于诊断产品，不是模式原生涡度/散度场。`);draw(m,-a,a,['#3a2e8c','#356fba','#62bbc6','#f1efdc','#e7a45d','#bb4141']);$('validTime').textContent=res[0]?.hourly?.time?.[fh]||'—'}
export async function vorticity850(){return windDiag(850,'vor')} export async function divergence200(){return windDiag(200,'div')}
export async function typhoon(){active='台风专题';$('map').classList.add('hidden');$('soundingChart').classList.add('hidden');$('soundingMetrics').classList.add('hidden');$('dynamicsMap').classList.add('hidden');$('productTitle').textContent='台风专题';$('productDescription').textContent='权威热带气旋信息入口';$('sourceText').textContent='JMA / RSMC Tokyo';$('validTime').textContent='实时更新';$('modelText').textContent='官方台风信息';$('productNotes').innerHTML='<p>本页不自行推算或伪造台风路径。当前版本提供日本气象厅（JMA/RSMC Tokyo）权威台风信息入口；后续只有在稳定获得可程序化读取的官方轨迹数据后，才会在 App 内绘制路径。</p><p><a class="external-link" href="https://www.jma.go.jp/bosai/map.html#5/20/120/&elem=root&typhoon=all&contents=typhoon" target="_blank" rel="noopener">打开 JMA 台风信息</a></p>'}
const loaders={omega700,omega500,vorticity850,divergence200,typhoon};
async function run(name){try{$('statusBadge').textContent='加载中…';await loaders[name]();$('statusBadge').textContent='数据已更新'}catch(e){console.error(e);$('statusBadge').textContent='加载失败';$('productNotes').innerHTML+=`<p><strong>错误：</strong>${e.message||e}</p>`}}
document.querySelectorAll('.dynamic-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.product-tab,.dynamic-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');run(b.dataset.dynamic)}));document.querySelectorAll('.product-tab').forEach(b=>b.addEventListener('click',()=>{$('dynamicsMap').classList.add('hidden');$('map').classList.remove('hidden');active=null}));$('modelSelect')?.addEventListener('change',()=>{if(active){const b=document.querySelector('.dynamic-tab.active');if(b)run(b.dataset.dynamic)}});$('forecastHour')?.addEventListener('change',()=>{if(active){const b=document.querySelector('.dynamic-tab.active');if(b)run(b.dataset.dynamic)}});
