const MODELS={cma:'https://api.open-meteo.com/v1/cma',ecmwf:'https://api.open-meteo.com/v1/ecmwf',gfs:'https://api.open-meteo.com/v1/gfs'};
const LATS=[15,20,25,30,35,40,45,50,55],LONS=[75,81,87,93,99,105,111,117,123,129,135];
const LEVELS=[1000,925,850,700,600,500,400,300,250,200];
const $=id=>document.getElementById(id);let mmap,mlayer,active=null;
function points(){const a=[];for(const lat of LATS)for(const lon of LONS)a.push({lat,lon});return a}
async function request(lat,lon,vars){const model=$('modelSelect')?.value||'cma',q=new URLSearchParams({latitude:Array.isArray(lat)?lat.join(','):lat,longitude:Array.isArray(lon)?lon.join(','):lon,hourly:vars.join(','),forecast_hours:'73',timezone:'GMT',wind_speed_unit:'ms'}),r=await fetch(`${MODELS[model]}?${q}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(d?.error)throw new Error(d.reason||'数据源错误');return Array.isArray(d)?d:[d]}
function matrix(res,key,i){const out=[];for(let r=0;r<LATS.length;r++){const row=[];for(let c=0;c<LONS.length;c++)row.push(Number(res[r*LONS.length+c]?.hourly?.[key]?.[i]));out.push(row)}return out}
function flat(m){return m.flat().filter(Number.isFinite)}
function uv(speed,dir){const u=[],v=[];for(let r=0;r<speed.length;r++){u[r]=[];v[r]=[];for(let c=0;c<speed[r].length;c++){const th=(Number(dir[r][c])||0)*Math.PI/180,s=Number(speed[r][c]);u[r][c]=-s*Math.sin(th);v[r][c]=-s*Math.cos(th)}}return{u,v}}
export function specificHumidity(tempC,rh,pHpa){const t=Number(tempC),r=Math.max(0,Math.min(100,Number(rh))),p=Number(pHpa);if(![t,r,p].every(Number.isFinite)||p<=0)return NaN;const es=6.112*Math.exp((17.67*t)/(t+243.5)),e=r/100*es,w=.622*e/Math.max(.01,p-e);return w/(1+w)}
function qMatrix(t,rh,p){return t.map((row,r)=>row.map((x,c)=>specificHumidity(x,rh[r][c],p)))}
function fluxComponents(q,speed,dir){const {u,v}=uv(speed,dir),qu=[],qv=[],mag=[];for(let r=0;r<q.length;r++){qu[r]=[];qv[r]=[];mag[r]=[];for(let c=0;c<q[r].length;c++){qu[r][c]=q[r][c]*u[r][c];qv[r][c]=q[r][c]*v[r][c];mag[r][c]=Math.hypot(qu[r][c],qv[r][c])*1000}}return{qu,qv,mag}}
function divergence(u,v){const R=6371000,out=[];for(let r=0;r<LATS.length;r++){out[r]=[];for(let c=0;c<LONS.length;c++){const rm=Math.max(0,r-1),rp=Math.min(LATS.length-1,r+1),cm=Math.max(0,c-1),cp=Math.min(LONS.length-1,c+1),lat=LATS[r]*Math.PI/180,dx=R*Math.cos(lat)*(LONS[cp]-LONS[cm])*Math.PI/180,dy=R*(LATS[rp]-LATS[rm])*Math.PI/180;out[r][c]=((u[r][cp]-u[r][cm])/dx+(v[rp][c]-v[rm][c])/dy)*1e8}}return out}
function ensureMap(){if(mmap)return;mmap=L.map('moistureMap',{minZoom:3,maxZoom:9}).setView([35,105],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:9,attribution:'&copy; OpenStreetMap contributors'}).addTo(mmap)}
function color(v,min,max,pal){if(!Number.isFinite(v))return[0,0,0,0];const z=Math.max(0,Math.min(1,(v-min)/(max-min)))*(pal.length-1),i=Math.min(pal.length-2,Math.floor(z)),f=z-i,hex=h=>h.match(/\w\w/g).map(x=>parseInt(x,16)),a=hex(pal[i]),b=hex(pal[i+1]);return[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,a[2]+(b[2]-a[2])*f,220]}
function bilinear(a,b,c,d,x,y){return a*(1-x)*(1-y)+b*x*(1-y)+c*(1-x)*y+d*x*y}
function draw(m,min,max,pal){ensureMap();if(mlayer)mmap.removeLayer(mlayer);const c=document.createElement('canvas'),w=520,h=340;c.width=w;c.height=h;const x=c.getContext('2d'),img=x.createImageData(w,h);for(let py=0;py<h;py++){const gy=(1-py/(h-1))*(m.length-1),r=Math.min(m.length-2,Math.floor(gy)),ty=gy-r;for(let px=0;px<w;px++){const gx=px/(w-1)*(m[0].length-1),cc=Math.min(m[0].length-2,Math.floor(gx)),tx=gx-cc,val=bilinear(m[r][cc],m[r][cc+1],m[r+1][cc],m[r+1][cc+1],tx,ty),q=color(val,min,max,pal),k=(py*w+px)*4;img.data[k]=q[0];img.data[k+1]=q[1];img.data[k+2]=q[2];img.data[k+3]=q[3]}}x.putImageData(img,0,0);mlayer=L.imageOverlay(c.toDataURL(),[[LATS[0],LONS[0]],[LATS.at(-1),LONS.at(-1)]],{opacity:.74}).addTo(mmap);setTimeout(()=>mmap.invalidateSize(),0)}
function setLegend(background,left,right){const bar=$('legendBar'),labels=$('legendLabels');if(bar){bar.className='legend-bar';bar.style.background=background}if(labels)labels.innerHTML=`<span>${left}</span><span>${right}</span>`}
function activate(title,note){active=title;$('map').classList.add('hidden');$('dynamicsMap')?.classList.add('hidden');$('soundingChart').classList.add('hidden');$('soundingMetrics').classList.add('hidden');$('sectionChart').classList.add('hidden');$('moistureMap').classList.remove('hidden');$('sectionControl').classList.add('hidden');$('productTitle').textContent=title;$('productDescription').textContent=note;$('sourceText').textContent='Open-Meteo pressure levels → derived';$('modelText').textContent=$('modelSelect').selectedOptions[0]?.textContent||'模式';$('productNotes').innerHTML=`<p>${note}</p>`}
export async function moistureFlux850(){activate('850 hPa 水汽通量','由模式 850 hPa 温度、相对湿度、风速/风向推导比湿与水平水汽通量；属于 derived 诊断量。');setLegend('linear-gradient(90deg,#112f5c,#1e78aa,#38b6ad,#8bcf78,#e7dc58,#df7b45,#b53e50)','弱','强');const fh=Number($('forecastHour')?.value||0),res=await request(points().map(p=>p.lat),points().map(p=>p.lon),['temperature_850hPa','relative_humidity_850hPa','wind_speed_850hPa','wind_direction_850hPa']),t=matrix(res,'temperature_850hPa',fh),rh=matrix(res,'relative_humidity_850hPa',fh),s=matrix(res,'wind_speed_850hPa',fh),d=matrix(res,'wind_direction_850hPa',fh),q=qMatrix(t,rh,850),f=fluxComponents(q,s,d),hi=Math.max(5,...flat(f.mag));draw(f.mag,0,hi,['#112f5c','#1e78aa','#38b6ad','#8bcf78','#e7dc58','#df7b45','#b53e50']);$('validTime').textContent=res[0]?.hourly?.time?.[fh]||'—';$('productNotes').innerHTML+='<p>显示量为 q×|V|，单位 g·kg⁻¹·m·s⁻¹ 的等价缩放表达（数值采用 q[kg/kg]×V[m/s]×1000）。</p>'}
export async function moistureFluxDivergence850(){activate('850 hPa 水汽通量散度','由模式温湿风场推导水汽通量后，在当前采样网格采用球面有限差分计算散度；属于 derived 诊断量。');setLegend('linear-gradient(90deg,#3b2b88,#356fba,#62bbc6,#f2f0de,#e3a45f,#b84242)','辐合','辐散');const fh=Number($('forecastHour')?.value||0),res=await request(points().map(p=>p.lat),points().map(p=>p.lon),['temperature_850hPa','relative_humidity_850hPa','wind_speed_850hPa','wind_direction_850hPa']),t=matrix(res,'temperature_850hPa',fh),rh=matrix(res,'relative_humidity_850hPa',fh),s=matrix(res,'wind_speed_850hPa',fh),d=matrix(res,'wind_direction_850hPa',fh),q=qMatrix(t,rh,850),f=fluxComponents(q,s,d),m=divergence(f.qu,f.qv),a=Math.max(.2,...flat(m).map(Math.abs));draw(m,-a,a,['#3b2b88','#356fba','#62bbc6','#f2f0de','#e3a45f','#b84242']);$('validTime').textContent=res[0]?.hourly?.time?.[fh]||'—';$('productNotes').innerHTML+='<p>负值表示水汽通量辐合、正值表示辐散；数值缩放为 10⁻⁸ s⁻¹ 量级，仅用于采样网格诊断。</p>'}
export function sectionPoints(a,b,n=17){const out=[];for(let i=0;i<n;i++){const f=i/(n-1);out.push({lat:a.lat+(b.lat-a.lat)*f,lon:a.lon+(b.lon-a.lon)*f})}return out}
function haversineKm(a,b){const R=6371,d=Math.PI/180,dLat=(b.lat-a.lat)*d,dLon=(b.lon-a.lon)*d,p1=a.lat*d,p2=b.lat*d,h=Math.sin(dLat/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(h)))}
function cumulativeDistanceKm(pts){const x=[0];for(let i=1;i<pts.length;i++)x.push(x[i-1]+haversineKm(pts[i-1],pts[i]));return x.map(v=>Number(v.toFixed(1)))}
function sectionBaseVars(){const v=[];for(const p of LEVELS)v.push(`temperature_${p}hPa`,`relative_humidity_${p}hPa`);return v}
function sectionOmegaVars(){return LEVELS.map(p=>`vertical_velocity_${p}hPa`)}
export async function verticalSection(){active='垂直剖面';$('map').classList.add('hidden');$('dynamicsMap')?.classList.add('hidden');$('moistureMap').classList.add('hidden');$('soundingChart').classList.add('hidden');$('soundingMetrics').classList.add('hidden');$('sectionChart').classList.remove('hidden');$('sectionControl').classList.remove('hidden');setLegend('linear-gradient(90deg,#440154,#31688e,#35b779,#fde725)','低 RH','高 RH');$('productTitle').textContent='垂直剖面';$('productDescription').textContent='沿两点连线采样的模式温湿与可用垂直速度剖面';$('sourceText').textContent='Open-Meteo pressure levels';$('modelText').textContent=$('modelSelect').selectedOptions[0]?.textContent||'模式';const a={lat:Number($('sectionLat1').value),lon:Number($('sectionLon1').value)},b={lat:Number($('sectionLat2').value),lon:Number($('sectionLon2').value)};if(![a.lat,a.lon,b.lat,b.lon].every(Number.isFinite))throw new Error('剖面端点无效');const pts=sectionPoints(a,b),lats=pts.map(p=>p.lat),lons=pts.map(p=>p.lon),fh=Number($('forecastHour')?.value||0),res=await request(lats,lons,sectionBaseVars()),z=LEVELS.map(p=>pts.map((_,i)=>Number(res[i]?.hourly?.[`relative_humidity_${p}hPa`]?.[fh]))),temp=LEVELS.map(p=>pts.map((_,i)=>Number(res[i]?.hourly?.[`temperature_${p}hPa`]?.[fh]))),x=cumulativeDistanceKm(pts);let omega=null,omegaAvailable=false,omegaNote='';try{const omegaRes=await request(lats,lons,sectionOmegaVars());omega=LEVELS.map(p=>pts.map((_,i)=>Number(omegaRes[i]?.hourly?.[`vertical_velocity_${p}hPa`]?.[fh])));omegaAvailable=omega.flat().some(Number.isFinite)}catch(e){omegaAvailable=false;omegaNote='当前模式/层次的垂直速度字段不可用，已自动降级为温度与湿度剖面。'}const traces=[{z,x,y:LEVELS,type:'heatmap',colorscale:'YlGnBu',zmin:0,zmax:100,colorbar:{title:'RH %'},hovertemplate:'距离 %{x:.0f} km<br>%{y} hPa<br>RH %{z:.0f}%<extra></extra>'},{z:temp,x,y:LEVELS,type:'contour',showscale:false,contours:{coloring:'none',showlabels:true},line:{width:1.2},hoverinfo:'skip'}];if(omegaAvailable)traces.push({z:omega,x,y:LEVELS,type:'contour',showscale:false,contours:{coloring:'none',start:-1,end:1,size:.2},line:{width:1,dash:'dot'},hoverinfo:'skip'});await Plotly.react($('sectionChart'),traces,{paper_bgcolor:'#07141f',plot_bgcolor:'#07141f',font:{color:'#dcecf5'},margin:{l:70,r:30,t:55,b:60},title:{text:`垂直剖面：(${a.lat.toFixed(1)},${a.lon.toFixed(1)}) → (${b.lat.toFixed(1)},${b.lon.toFixed(1)})`,x:.02},xaxis:{title:'沿线距离 (km)'},yaxis:{title:'气压 (hPa)',type:'log',autorange:'reversed',tickvals:LEVELS}},{responsive:true,displaylogo:false});$('validTime').textContent=res[0]?.hourly?.time?.[fh]||'—';$('productNotes').innerHTML=`<p>底色：相对湿度；实线等值线：温度；${omegaAvailable?'点线：模式垂直速度。':'垂直速度未绘制。'}剖面由两端点之间 17 个等距经纬度点采样形成，横轴为累计大圆距离，不代表原始模式全分辨率切片。</p>${omegaNote?`<p>${omegaNote}</p>`:''}`}
const loaders={moistureFlux850,moistureFluxDivergence850,verticalSection};async function run(name){try{$('statusBadge').textContent='加载中…';await loaders[name]();$('statusBadge').textContent='数据已更新'}catch(e){console.error(e);$('statusBadge').textContent='加载失败';$('productNotes').innerHTML+=`<p><strong>错误：</strong>${e.message||e}</p>`}}
document.querySelectorAll('.moisture-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.product-tab,.dynamic-tab,.moisture-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');run(b.dataset.moisture)}));document.querySelectorAll('.product-tab,.dynamic-tab').forEach(b=>b.addEventListener('click',()=>{$('moistureMap').classList.add('hidden');$('sectionChart').classList.add('hidden');$('sectionControl').classList.add('hidden');active=null}));$('loadSection')?.addEventListener('click',()=>run('verticalSection'));$('modelSelect')?.addEventListener('change',()=>{const b=document.querySelector('.moisture-tab.active');if(b)run(b.dataset.moisture)});$('forecastHour')?.addEventListener('change',()=>{const b=document.querySelector('.moisture-tab.active');if(b)run(b.dataset.moisture)});$('refreshBtn')?.addEventListener('click',e=>{const b=document.querySelector('.moisture-tab.active');if(!b)return;e.stopImmediatePropagation();run(b.dataset.moisture)},true);
